# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd7562ab19393fdd02be9af0992f6121a73e8540104cc85418dd2e096d66de18c11ea9aa003da3e2ccfcb41f177ad56ed33f3db4434f4397f41b5ae8167fc9b2

test:
  secret_key_base: 3f43e7d60835e6225ec1b5b995abc3b7ae32fab6acd748cdf81282b4603844da70be6ea0bcc0579bcd5876561f11441ff91265f7601f2a2935ce956335a256e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
